obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]

inflation_radius: 0.3

cost_scaling_factor: 5.0

# 传感器配置
observation_sources: laser_scan
laser_scan: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}