DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.0  # 对于全向轮设为适当值
  min_vel_y: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0
  
  goal_distance_bias: 24.0
  path_distance_bias: 24.0
  
  sim_time: 2.0